version: 1.0.{build}
image: Visual Studio 2019

configuration: Release

install:
  - ps: .\install-font.ps1

build_script:
  - cmd: pip install pyinstaller
  - cmd: pyinstaller --onefile --windowed egogram_app.py

artifacts:
  - path: dist\*
    name: EgogramApp
